spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phonebook
    username: Vivi
    password: Vivi_123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop